import type { AuthCase, Criterion, DenialFinding, EvidenceGap, EvidenceItem, Facility, Patient } from "../types";
import { isEvidenceApprovedForPacket, validateEvidenceItem } from "../evidence";

type PacketInput = {
  authCase: AuthCase;
  facility: Facility;
  patient: Patient;
  denialFinding: DenialFinding;
  criteria: Criterion[];
  evidenceItems: EvidenceItem[];
  evidenceGaps: EvidenceGap[];
  generatedBy: string;
  versionNumber: number;
  exportedAt?: string;
};

const clinicalVerbs = [
  "requires",
  "required",
  "needs",
  "needed",
  "monitor",
  "monitoring",
  "ambulate",
  "transfers",
  "wound",
  "therapy",
  "supervision",
  "medication",
  "blood pressure",
  "antibiotic"
];

function sentenceHasCitation(sentence: string) {
  return /\[(EV|DEN)-[A-Za-z0-9_-]+\]/.test(sentence);
}

function sentenceHasClinicalAssertion(sentence: string) {
  const lower = sentence.toLowerCase();
  return clinicalVerbs.some((term) => lower.includes(term));
}

export function blockUnsupportedClaims(markdown: string) {
  let section = "";
  const auditableLines: string[] = [];

  for (const rawLine of markdown.split("\n")) {
    const line = rawLine.trim();
    if (!line) continue;
    if (line.startsWith("## ")) {
      section = line.replace(/^##\s+/, "");
      continue;
    }
    if (line.startsWith("# ") || line.startsWith("Status:") || line.startsWith("Version:") || line.startsWith("Generated by:") || line.startsWith("Approved by:") || line.startsWith("Export timestamp:")) {
      continue;
    }
    if (line.startsWith("|") || line.startsWith("- Patient display:") || line.startsWith("- Facility:") || line.startsWith("- Plan:") || line.startsWith("- Service requested:") || line.startsWith("- Denial date:") || line.startsWith("- Appeal deadline:")) {
      continue;
    }
    if (["Missing or Attached Documentation", "Physician Attestation Placeholder", "Attachment Index", "Audit Footer"].includes(section)) {
      continue;
    }
    auditableLines.push(line);
  }

  const sentences = auditableLines
    .flatMap((line) => line.split(/(?<=[.!?])\s+/))
    .map((sentence) => sentence.trim())
    .filter(Boolean);

  const blocked = sentences.filter((sentence) => sentenceHasClinicalAssertion(sentence) && !sentenceHasCitation(sentence));

  return {
    ok: blocked.length === 0,
    blocked
  };
}

export function generatePacketMarkdown(input: PacketInput) {
  const approvedEvidence = input.evidenceItems.filter(isEvidenceApprovedForPacket);
  const invalidEvidence = input.evidenceItems.filter((item) => !validateEvidenceItem(item));
  const openGaps = input.evidenceGaps.filter((gap) => !gap.resolvedAt);
  const exportedAt = input.exportedAt ?? new Date().toISOString();

  const evidenceRows = approvedEvidence
    .map((item) => {
      const criterion = input.criteria.find((candidate) => candidate.id === item.criterionId);
      return `| ${criterion?.label ?? "Mapped criterion"} | ${item.normalizedSummary} [EV-${item.id}] | ${item.documentTitle} | ${item.pageNumber} | "${item.quote}" | ${item.reviewerStatus} |`;
    })
    .join("\n");

  const missingList = openGaps.length
    ? openGaps.map((gap) => `- ${gap.gapText} Owner: ${gap.suggestedOwner}. Reason: ${gap.whyNeeded}`).join("\n")
    : "- No open evidence gaps in the current draft.";

  const attachmentRows = input.criteria
    .map((criterion) => {
      const source = approvedEvidence.find((item) => item.criterionId === criterion.id);
      if (!source) {
        return `| ${criterion.label} | Pending source | 0 | Missing evidence checklist |`;
      }
      return `| ${criterion.label} | ${source.documentTitle} | ${source.pageNumber} | Supports cited criterion ${criterion.label} |`;
    })
    .join("\n");
  const denialRationale = input.denialFinding.payerRationale.replace(/\.$/, "");
  const evidenceBullets = approvedEvidence
    .map((item) => `- ${item.normalizedSummary.replace(/\.$/, "")} [EV-${item.id}].`)
    .join("\n");

  const markdown = `# AppealForge PAC Appeal Packet

Status: DRAFT - human approval required before approved export
Version: ${input.versionNumber}
Generated by: ${input.generatedBy}
Approved by: Pending human approval
Export timestamp: ${exportedAt}

## Cover Letter
To the Medicare Advantage reconsideration reviewer:

${input.facility.name} requests reconsideration of the denial for ${input.patient.syntheticLabel} for ${input.authCase.serviceType}. The denial reason in the notice is "${input.denialFinding.denialReason}" [DEN-${input.denialFinding.id}].

This draft packet uses only reviewer-accepted evidence items and source citations. AppealForge PAC does not make medical necessity decisions; it assembles evidence for human review.

## Patient and Service Summary
- Patient display: ${input.patient.syntheticLabel}
- Facility: ${input.facility.name}
- Plan: ${input.authCase.planName}
- Service requested: ${input.authCase.serviceType}
- Denial date: ${input.authCase.denialDate}
- Appeal deadline: ${input.authCase.appealDeadlineAt}

## Denial Reason
${denialRationale} [DEN-${input.denialFinding.id}].

## Clinical Necessity Summary
${evidenceBullets}

## Evidence Table
| Criterion | Evidence summary | Source document | Page | Exact quote | Reviewer status |
|---|---|---|---:|---|---|
${evidenceRows}

## Missing or Attached Documentation
${missingList}

## Physician Attestation Placeholder
I have reviewed the cited clinical evidence and confirm whether the appeal narrative accurately reflects the attached record. Signature, credentials, date, and expedited appeal statement may be added here by the physician reviewer.

## Attachment Index
| Attachment | Document | Pages | Purpose |
|---|---|---:|---|
${attachmentRows}

## Audit Footer
Generated by AppealForge PAC on ${exportedAt}. Packet version ${input.versionNumber}. Clinical content remains draft until human approval.`;

  const claimAudit = blockUnsupportedClaims(markdown);

  return {
    markdown,
    approvedEvidence,
    invalidEvidence,
    warnings: [
      ...invalidEvidence.map((item) => `Evidence item ${item.id} has an invalid citation and was excluded.`),
      ...claimAudit.blocked.map((sentence) => `Unsupported clinical claim blocked: ${sentence}`)
    ],
    claimAudit
  };
}
