import type { AuthCase, Criterion, DenialFinding, EvidenceGap, EvidenceItem, Facility, Patient } from "../types";
import { isEvidenceApprovedForPacket, validateEvidenceItem } from "../evidence";

export type PacketInput = {
  authCase: AuthCase;
  facility: Facility;
  patient: Patient;
  denialFinding: DenialFinding;
  criteria: Criterion[];
  evidenceItems: EvidenceItem[];
  evidenceGaps: EvidenceGap[];
  generatedBy: string;
  versionNumber: number;
  exportedAt?: string;
};

function escapeHtml(value: string | number | undefined) {
  return String(value ?? "")
    .replaceAll("&", "&amp;")
    .replaceAll("<", "&lt;")
    .replaceAll(">", "&gt;")
    .replaceAll('"', "&quot;")
    .replaceAll("'", "&#39;");
}

const clinicalVerbs = [
  "requires",
  "required",
  "needs",
  "needed",
  "monitor",
  "monitoring",
  "ambulate",
  "transfers",
  "wound",
  "therapy",
  "supervision",
  "medication",
  "blood pressure",
  "antibiotic"
];

function sentenceHasCitation(sentence: string) {
  return /\[(EV|DEN)-[A-Za-z0-9_-]+\]/.test(sentence);
}

function sentenceHasClinicalAssertion(sentence: string) {
  const lower = sentence.toLowerCase();
  return clinicalVerbs.some((term) => lower.includes(term));
}

export function blockUnsupportedClaims(markdown: string) {
  let section = "";
  const auditableLines: string[] = [];

  for (const rawLine of markdown.split("\n")) {
    const line = rawLine.trim();
    if (!line) continue;
    if (line.startsWith("## ")) {
      section = line.replace(/^##\s+/, "");
      continue;
    }
    if (line.startsWith("# ") || line.startsWith("Status:") || line.startsWith("Version:") || line.startsWith("Generated by:") || line.startsWith("Approved by:") || line.startsWith("Export timestamp:")) {
      continue;
    }
    if (line.startsWith("|") || line.startsWith("- Patient display:") || line.startsWith("- Facility:") || line.startsWith("- Plan:") || line.startsWith("- Service requested:") || line.startsWith("- Denial date:") || line.startsWith("- Appeal deadline:")) {
      continue;
    }
    if (["Missing or Attached Documentation", "Physician Attestation Placeholder", "Attachment Index", "Audit Footer"].includes(section)) {
      continue;
    }
    auditableLines.push(line);
  }

  const sentences = auditableLines
    .flatMap((line) => line.split(/(?<=[.!?])\s+/))
    .map((sentence) => sentence.trim())
    .filter(Boolean);

  const blocked = sentences.filter((sentence) => sentenceHasClinicalAssertion(sentence) && !sentenceHasCitation(sentence));

  return {
    ok: blocked.length === 0,
    blocked
  };
}

export function generatePacketMarkdown(input: PacketInput) {
  const approvedEvidence = input.evidenceItems.filter(isEvidenceApprovedForPacket);
  const invalidEvidence = input.evidenceItems.filter((item) => !validateEvidenceItem(item));
  const openGaps = input.evidenceGaps.filter((gap) => !gap.resolvedAt);
  const exportedAt = input.exportedAt ?? new Date().toISOString();

  const evidenceRows = approvedEvidence
    .map((item) => {
      const criterion = input.criteria.find((candidate) => candidate.id === item.criterionId);
      return `| ${criterion?.label ?? "Mapped criterion"} | ${item.normalizedSummary} [EV-${item.id}] | ${item.documentTitle} | ${item.pageNumber} | "${item.quote}" | ${item.reviewerStatus} |`;
    })
    .join("\n");

  const missingList = openGaps.length
    ? openGaps.map((gap) => `- ${gap.gapText} Owner: ${gap.suggestedOwner}. Reason: ${gap.whyNeeded}`).join("\n")
    : "- No open evidence gaps in the current draft.";

  const attachmentRows = input.criteria
    .map((criterion) => {
      const source = approvedEvidence.find((item) => item.criterionId === criterion.id);
      if (!source) {
        return `| ${criterion.label} | Pending source | 0 | Missing evidence checklist |`;
      }
      return `| ${criterion.label} | ${source.documentTitle} | ${source.pageNumber} | Supports cited criterion ${criterion.label} |`;
    })
    .join("\n");
  const denialRationale = input.denialFinding.payerRationale.replace(/\.$/, "");
  const evidenceBullets = approvedEvidence
    .map((item) => `- ${item.normalizedSummary.replace(/\.$/, "")} [EV-${item.id}].`)
    .join("\n");

  const markdown = `# AppealForge PAC Appeal Packet

Status: DRAFT - human approval required before approved export
Version: ${input.versionNumber}
Generated by: ${input.generatedBy}
Approved by: Pending human approval
Export timestamp: ${exportedAt}

## Cover Letter
To the Medicare Advantage reconsideration reviewer:

${input.facility.name} requests reconsideration of the denial for ${input.patient.syntheticLabel} for ${input.authCase.serviceType}. The denial reason in the notice is "${input.denialFinding.denialReason}" [DEN-${input.denialFinding.id}].

This draft packet uses only reviewer-accepted evidence items and source citations. AppealForge PAC does not make medical necessity decisions; it assembles evidence for human review.

## Patient and Service Summary
- Patient display: ${input.patient.syntheticLabel}
- Facility: ${input.facility.name}
- Plan: ${input.authCase.planName}
- Service requested: ${input.authCase.serviceType}
- Denial date: ${input.authCase.denialDate}
- Appeal deadline: ${input.authCase.appealDeadlineAt}

## Denial Reason
${denialRationale} [DEN-${input.denialFinding.id}].

## Clinical Necessity Summary
${evidenceBullets}

## Evidence Table
| Criterion | Evidence summary | Source document | Page | Exact quote | Reviewer status |
|---|---|---|---:|---|---|
${evidenceRows}

## Missing or Attached Documentation
${missingList}

## Physician Attestation Placeholder
I have reviewed the cited clinical evidence and confirm whether the appeal narrative accurately reflects the attached record. Signature, credentials, date, and expedited appeal statement may be added here by the physician reviewer.

## Attachment Index
| Attachment | Document | Pages | Purpose |
|---|---|---:|---|
${attachmentRows}

## Audit Footer
Generated by AppealForge PAC on ${exportedAt}. Packet version ${input.versionNumber}. Clinical content remains draft until human approval.`;

  const claimAudit = blockUnsupportedClaims(markdown);

  return {
    markdown,
    approvedEvidence,
    invalidEvidence,
    warnings: [
      ...invalidEvidence.map((item) => `Evidence item ${item.id} has an invalid citation and was excluded.`),
      ...claimAudit.blocked.map((sentence) => `Unsupported clinical claim blocked: ${sentence}`)
    ],
    claimAudit
  };
}

export function generatePacketHtml(input: PacketInput) {
  const packet = generatePacketMarkdown(input);
  const openGaps = input.evidenceGaps.filter((gap) => !gap.resolvedAt);
  const exportedAt = input.exportedAt ?? new Date().toISOString();

  const evidenceRows = packet.approvedEvidence
    .map((item) => {
      const criterion = input.criteria.find((candidate) => candidate.id === item.criterionId);
      return `<tr>
        <td>${escapeHtml(criterion?.label ?? "Mapped criterion")}</td>
        <td>${escapeHtml(item.normalizedSummary)} <span class="chip">EV-${escapeHtml(item.id)}</span></td>
        <td>${escapeHtml(item.documentTitle)}</td>
        <td class="page">${escapeHtml(item.pageNumber)}</td>
        <td><q>${escapeHtml(item.quote)}</q></td>
        <td>${escapeHtml(item.reviewerStatus.replaceAll("_", " "))}</td>
      </tr>`;
    })
    .join("");

  const gapRows = openGaps.length
    ? openGaps
        .map(
          (gap) => `<li>
            <strong>${escapeHtml(gap.gapText)}</strong>
            <span>${escapeHtml(gap.whyNeeded)} Owner: ${escapeHtml(gap.suggestedOwner)}.</span>
          </li>`
        )
        .join("")
    : "<li><strong>No open evidence gaps.</strong><span>Current draft has no missing evidence checklist items.</span></li>";

  const attachmentRows = input.criteria
    .map((criterion) => {
      const source = packet.approvedEvidence.find((item) => item.criterionId === criterion.id);
      return `<tr>
        <td>${escapeHtml(criterion.label)}</td>
        <td>${escapeHtml(source?.documentTitle ?? "Pending source")}</td>
        <td class="page">${escapeHtml(source?.pageNumber ?? 0)}</td>
        <td>${escapeHtml(source ? `Supports cited criterion ${criterion.label}` : "Missing evidence checklist")}</td>
      </tr>`;
    })
    .join("");

  const clinicalBullets = packet.approvedEvidence
    .map((item) => `<li>${escapeHtml(item.normalizedSummary.replace(/\.$/, ""))} <span class="chip">EV-${escapeHtml(item.id)}</span>.</li>`)
    .join("");

  const warningBlock = packet.warnings.length
    ? `<section class="warning"><h2>Unsupported Claim Warnings</h2>${packet.warnings.map((warning) => `<p>${escapeHtml(warning)}</p>`).join("")}</section>`
    : `<section class="pass"><h2>Citation Guard Passed</h2><p>All generated clinical assertions are linked to accepted evidence citations or case metadata.</p></section>`;

  const html = `<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <title>AppealForge PAC Draft Packet - ${escapeHtml(input.authCase.id)}</title>
  <style>
    :root {
      --ink: #17202a;
      --muted: #5d665e;
      --paper: #f8f5ef;
      --paper-edge: #d8cfbf;
      --teal: #007f72;
      --amber: #9c6b3b;
      --coral: #b9472f;
    }
    * { box-sizing: border-box; }
    body { margin: 0; background: #08111f; color: var(--ink); font-family: Georgia, Charter, Cambria, serif; }
    .page { width: min(980px, calc(100% - 32px)); margin: 32px auto; background: var(--paper); border: 1px solid var(--paper-edge); box-shadow: 0 24px 80px rgba(0,0,0,.35); padding: 52px; position: relative; }
    .watermark { position: absolute; inset: 180px auto auto 130px; transform: rotate(-24deg); font-size: 110px; font-weight: 700; color: rgba(185,71,47,.09); pointer-events: none; }
    header { border-bottom: 1px solid var(--paper-edge); padding-bottom: 22px; margin-bottom: 28px; display: flex; justify-content: space-between; gap: 24px; }
    h1 { margin: 0; font-size: 38px; letter-spacing: 0; }
    h2 { margin: 28px 0 10px; font-size: 20px; letter-spacing: 0; }
    p, li { font-size: 15px; line-height: 1.7; }
    .meta { color: var(--muted); font-family: Inter, Arial, sans-serif; font-size: 12px; line-height: 1.7; }
    .status { border: 1px solid rgba(156,107,59,.35); color: var(--amber); padding: 8px 12px; border-radius: 999px; font-family: Inter, Arial, sans-serif; font-size: 12px; font-weight: 700; white-space: nowrap; height: fit-content; }
    .grid { display: grid; grid-template-columns: repeat(2, minmax(0, 1fr)); gap: 10px 18px; }
    .field { border: 1px solid var(--paper-edge); border-radius: 10px; padding: 10px 12px; background: rgba(255,255,255,.36); }
    .label { display: block; color: var(--muted); font-family: Inter, Arial, sans-serif; font-size: 11px; text-transform: uppercase; letter-spacing: .08em; margin-bottom: 4px; }
    table { width: 100%; border-collapse: collapse; margin-top: 12px; font-family: Inter, Arial, sans-serif; font-size: 12px; }
    th, td { border-bottom: 1px solid var(--paper-edge); padding: 10px 8px; text-align: left; vertical-align: top; }
    th { color: #30443f; font-size: 11px; text-transform: uppercase; letter-spacing: .08em; }
    q { color: #283630; }
    .page td.page, .page th.page { text-align: right; font-variant-numeric: tabular-nums; }
    .chip { display: inline-block; border: 1px solid rgba(0,127,114,.28); color: var(--teal); border-radius: 999px; padding: 2px 8px; font-family: Inter, Arial, sans-serif; font-size: 11px; font-weight: 700; white-space: nowrap; }
    .warning, .pass { border-radius: 12px; padding: 14px 16px; margin: 20px 0; font-family: Inter, Arial, sans-serif; }
    .warning { border: 1px solid rgba(185,71,47,.28); background: rgba(185,71,47,.08); color: var(--coral); }
    .pass { border: 1px solid rgba(0,127,114,.24); background: rgba(0,127,114,.08); color: var(--teal); }
    .gap-list { padding-left: 20px; }
    .gap-list span { display: block; color: var(--muted); }
    footer { margin-top: 34px; padding-top: 16px; border-top: 1px solid var(--paper-edge); color: var(--muted); font-family: Inter, Arial, sans-serif; font-size: 11px; line-height: 1.6; }
    @media print {
      body { background: white; }
      .page { margin: 0; width: 100%; min-height: 100vh; box-shadow: none; border: 0; }
    }
  </style>
</head>
<body>
  <main class="page">
    <div class="watermark">DRAFT</div>
    <header>
      <div>
        <h1>Appeal Packet</h1>
        <div class="meta">Generated by AppealForge PAC | Version ${escapeHtml(input.versionNumber)} | ${escapeHtml(exportedAt)}</div>
      </div>
      <div class="status">DRAFT - Human Approval Required</div>
    </header>

    ${warningBlock}

    <section>
      <h2>Cover Letter</h2>
      <p>To the Medicare Advantage reconsideration reviewer:</p>
      <p>${escapeHtml(input.facility.name)} requests reconsideration of the denial for ${escapeHtml(input.patient.syntheticLabel)} for ${escapeHtml(input.authCase.serviceType)}. The denial reason in the notice is "${escapeHtml(input.denialFinding.denialReason)}" <span class="chip">DEN-${escapeHtml(input.denialFinding.id)}</span>.</p>
      <p>This draft packet uses only reviewer-accepted evidence items and source citations. AppealForge PAC does not make medical necessity decisions; it assembles evidence for human review.</p>
    </section>

    <section>
      <h2>Patient and Service Summary</h2>
      <div class="grid">
        <div class="field"><span class="label">Patient display</span>${escapeHtml(input.patient.syntheticLabel)}</div>
        <div class="field"><span class="label">Facility</span>${escapeHtml(input.facility.name)}</div>
        <div class="field"><span class="label">Plan</span>${escapeHtml(input.authCase.planName)}</div>
        <div class="field"><span class="label">Service requested</span>${escapeHtml(input.authCase.serviceType)}</div>
        <div class="field"><span class="label">Denial date</span>${escapeHtml(input.authCase.denialDate)}</div>
        <div class="field"><span class="label">Appeal deadline</span>${escapeHtml(input.authCase.appealDeadlineAt)}</div>
      </div>
    </section>

    <section>
      <h2>Denial Reason</h2>
      <p>${escapeHtml(input.denialFinding.payerRationale.replace(/\.$/, ""))} <span class="chip">DEN-${escapeHtml(input.denialFinding.id)}</span>.</p>
    </section>

    <section>
      <h2>Clinical Necessity Summary</h2>
      <ul>${clinicalBullets}</ul>
    </section>

    <section>
      <h2>Evidence Table</h2>
      <table>
        <thead><tr><th>Criterion</th><th>Evidence summary</th><th>Source document</th><th class="page">Page</th><th>Exact quote</th><th>Reviewer status</th></tr></thead>
        <tbody>${evidenceRows}</tbody>
      </table>
    </section>

    <section>
      <h2>Missing or Attached Documentation</h2>
      <ul class="gap-list">${gapRows}</ul>
    </section>

    <section>
      <h2>Physician Attestation Placeholder</h2>
      <p>I have reviewed the cited clinical evidence and confirm whether the appeal narrative accurately reflects the attached record.</p>
      <div class="grid">
        <div class="field"><span class="label">Physician signature</span>&nbsp;</div>
        <div class="field"><span class="label">Credentials</span>&nbsp;</div>
        <div class="field"><span class="label">Date</span>&nbsp;</div>
        <div class="field"><span class="label">Expedited statement</span>&nbsp;</div>
      </div>
    </section>

    <section>
      <h2>Attachment Index</h2>
      <table>
        <thead><tr><th>Attachment</th><th>Document</th><th class="page">Pages</th><th>Purpose</th></tr></thead>
        <tbody>${attachmentRows}</tbody>
      </table>
    </section>

    <footer>
      Generated by AppealForge PAC on ${escapeHtml(exportedAt)}. Packet version ${escapeHtml(input.versionNumber)}. Clinical content remains draft until human approval. Synthetic demo only.
    </footer>
  </main>
</body>
</html>`;

  return {
    html,
    warnings: packet.warnings,
    claimAudit: packet.claimAudit,
    approvedEvidence: packet.approvedEvidence
  };
}
